name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    if: ${{ github.event.repository.private }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}

      # - name: Run pre-commit
      #   uses: autowarefoundation/autoware-github-actions/pre-commit@v1
      #   with:
      #     pre-commit-config: .pre-commit-config.yaml
      #     token: ${{ steps.generate-token.outputs.token }}

      # shfmt requires Go 1.16+
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.16

      - name: Install pre-commit
        run: |
          python -m pip install pre-commit
        shell: bash

      - name: Run pre-commit
        run: |
          pre-commit run -a --show-diff-on-failure --color=always --config ${{ inputs.pre-commit-config }}
        shell: bash

      - name: Push pre-commit fixes
        if: always() # Push changes even when pre-commit fails
        run: |
          if ! git diff --quiet; then
            git add -u
            git commit -m "pre-commit fixes"
            git push
          fi
        shell: bash
